<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script
			  src="https://code.jquery.com/jquery-3.4.1.min.js"
			  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
			  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="js/lightbox/css/lightbox.min.css">
    <!-- Lightbox -->
    <script src="js/lightbox/js/lightbox.min.js"></script>
    <title>Galería</title>
</head>

<body class="container">
    <header class="jumbotron">
        <h3><i class="fa fa-camera"></i> Galeria de fotos</h3>
        <hr>
        Usa el script <a href="https://lokeshdhakar.com/projects/lightbox2/" target="_blank">lightbox 2</a> para el efecto de zoom sobre las fotos.<br>
        Codigo <a href="https://github.com/2daw-jovellanos/foto-galeria-lite" target="_blank">aquí</a>
    </header>
    <?php if ($error_msg ?? "") { ?>
        <div class="alert alert-danger"><?= $error_msg ?></div>
    <?php } ?>
    <div class="text-right m-2">
        <form action="." enctype="multipart/form-data" method="POST">
            <input class="btn btn-primary" type="file" name="foto"> <button type="Submit" class="btn btn-success">Subir</button>
        </form>
    </div>
    <section class="row">
        <?php foreach ($fotos as $foto) { ?>
            <div class="col-md-3 col-lg-2 mb-2">
                <!-- margin bottom 2-->
                <div class="card h-100">
                    <!-- height 100%-->
                    <div class="card-header">
                        <?= $foto["name"] ?>
                    </div>
                    <a href="<?= $foto["src"] ?>" data-lightbox="<?= $foto["name"]?>" data-title="<?= $foto["name"]?>">
                        <img class=" card-img" src="<?= $foto["src"] ?>" alt="Foto <?= $foto["src"] ?>">
                    </a>
                    <div class="card-body">
                        Size: <?= $foto["size"] ?> Bytes
                    </div>
                </div>
            </div>

        <?php } ?>
    </section>
</body>

</html>